service: skillquest-controller

plugins:
  - serverless-offline

package:
  exclude:
    - node_modules/**/aws-sdk/**
    - ./src/**/*.spec.*
    - .eslintrc*
    - .prettierrc*
    - .vscode*
    - README*
    - ./**/__tests__/**
    - .env

custom:
  keepWarm:
    prod: true
    notprod: false
  dbHost:
    notprod: skillquestdev.mvu8r.mongodb.net

provider:
  name: aws
  runtime: nodejs14.x
  profile: skillquest
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  versionFunctions: false
  endpointType: REGIONAL
  memorySize: 256
  environment:
    SERVERLESS_REGION: ${self:provider.region}
    SERVERLESS_STAGE: ${self:provider.stage}
    SERVERLESS_SERVICE: ${self:service}
    MONGODB_PASSWORD: ${ssm:skillquest-controller-db-pw~true}
    MONGODB_USER: controller
    MONGODB_HOST: ${self:custom.dbHost.${self:provider.stage}, self:custom.dbHost.notprod}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - states:StartExecution
            - s3:*
            - dynamodb:*
            - rds:*
            - secretsmanager:GetSecretValue
            - events:PutEvents
            - events:RemoveTargets
            - lambda:InvokeFunction
          Resource:
            - '*'
        - Effect: Allow
          Action:
            - sqs:ListQueues
            - sqs:DeleteMessage
            - sqs:GetQueueUrl
            - sqs:ReceiveMessage
            - sqs:SendMessage
          Resource:
            - '*'
  eventBridge:
    useCloudFormation: true
functions:
  rest-api:
    handler: src/lambdas/rest-api.handler
    name: ${self:service}-rest-api-${self:provider.stage}
    timeout: 30
    events:
      - http:
          path: /
          method: any
          cors: true
          private: false
      - http:
          path: /{proxy+}
          method: any
          cors: true
          private: false
      - schedule:
          rate: rate(10 minutes)
          enabled: ${self:custom.keepWarm.${self:provider.stage}, self:custom.keepWarm.notprod}
          input:
            type: warmer
